version: '2'
services:
    nginx_proxy:
        image: jwilder/nginx-proxy
        container_name: nginx_proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./certs:/etc/nginx/certs:ro
            - ./vhost.d:/etc/nginx/vhost.d:ro
            - /usr/share/nginx/html
        networks:
            - front
    letsencrypt_companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./certs:/etc/nginx/certs:rw
            - ./vhost.d:/etc/nginx/vhost.d:rw
        volumes_from:
            - nginx_proxy
networks:
    front:
        driver: bridge
